bots:
  - import: (data)/common/keep-internet-working.yaml
  - import: (data)/services/uptime-robot.yaml
  - name: authelia-oidc-allow
    expression:
      all:
        - 'path.matches("^/(api/oidc/.*|jwks\\.json)$")'
        - 'host.startsWith("authelia.")'
    action: ALLOW
  - name: catch-all-challenge
    path_regex: .*
    action: CHALLENGE

status_codes:
  CHALLENGE: 403
  DENY: 403

openGraph:
  enabled: false
